export default [
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 1,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-15',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'BRDNLbN5KeiLpVvrLPD7CE6gkPKp85t9MP956',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: '0MzEyBEPAJtm83zdmPxpSY0Y166jd6urZRkan',
    account_owner: null,
    amount: 5000,
    authorized_date: '2020-06-08',
    category: ['Transfer', 'Debit'],
    category_id: '21006000',
    date: '2020-06-08',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name:
      'ONLINE TRANSFER TO HODNETT H WAY2SAVE CHECKING XXXXXX3888 REF #IB0894PQJW ON 06/08/20',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'AMLmwomZyetmZjnrmYVESQRoe3NpeLf6aZXVM',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 5000,
    authorized_date: null,
    category: ['Service', 'Financial', 'Stock Brokers'],
    category_id: '18020003',
    date: '2020-06-09',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'Robinhood',
    payment_channel: 'online',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'JdkOaDOVmeixkXrOxKD4SOKLPaZpPDubzAEYr',
    transaction_type: 'place',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 3265.37,
    authorized_date: null,
    category: ['Payment', 'Credit Card'],
    category_id: '16001000',
    date: '2020-06-02',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'WF Credit Card AUTO PAY 200602 90495290659214 HODNETT,HUNTER C',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'w43jZQjYDVcn63zKnke9c6xJ7QZD7yCL4ewV9',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 1000,
    authorized_date: null,
    category: ['Service', 'Financial', 'Stock Brokers'],
    category_id: '18020003',
    date: '2020-05-27',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'Robinhood',
    payment_channel: 'online',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: '8Mo1bj1vw9t41EvB47xLi4rwkA1ak3Hy7mjMA',
    transaction_type: 'place',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 537.84,
    authorized_date: null,
    category: ['Payment', 'Credit Card'],
    category_id: '16001000',
    date: '2020-06-11',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'AMEX EPAYMENT ACH PMT 200611 A4248 HUNTER HODNETT',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: 'ACH',
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'rmD7AY7eJohn45VmnqjOc9NdgQJ7gEcBOK1vk',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 1,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-05-22',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'DMPQq7QbAetOZmxBO83eiN1XdaYJdKCZazA5B',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 16,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-05-26',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: '7zQg50gAd7srDLvqrZmJTp75AXwdADUQK4pej',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: '0MzEyBEPAJtm83zdmPxpSY0Y166jd6urZRkan',
    account_owner: null,
    amount: 0.06,
    authorized_date: null,
    category: ['Tax', 'Payment'],
    category_id: '20002000',
    date: '2020-05-27',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'FEDERAL TAX WITHHELD',
    payment_channel: 'online',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'ZjDvBxvV0wSvrndbvkxQted0ox7gopHRyzpmE',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 4,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-05-27',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'JdkOaDOVmeixkXrOxKD4SOKLPaZpPDubzAEjv',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 100,
    authorized_date: null,
    category: ['Transfer', 'Debit'],
    category_id: '21006000',
    date: '2020-05-29',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name:
      'RECURRING TRANSFER TO HODNETT H REF #OP0878FWTB WAY2SAVE SAVINGS SAVINGS',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'BRDNLbN5KeiLpVvrLPDZs9ykBJjLB5c9p8w1r',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 12,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-01',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: '3eoOjKO3m5UAV7npAOZqhA6VQPzkQqcK5zwap',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 3,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-02',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'dbvg7zgeRKsDBka3D86jHAqg7Q1v7Pcbn8gBP',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 4,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-04',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'n3dD1QDebJsNVxbANLkgHxKv7yJ87qUAmM3ra',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 2,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-03',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'Y0LrParVvdh34jvM3KaYhNbZ3goM3VCQ6nD0N',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 3,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-05',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'O1r0930VDesA8V5LAw3Zh6maRN7ORjC87ZbwV',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 4,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-08',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'oyw1qQ1eJ8t6yPQJ6DARSzALJOPgJ9UB1dK8a',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 3,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-09',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'xay9oQ9e1YTqLK5YqA8os6Pb97L59ECM1ABe0',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 1,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-10',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: '4MOE4kEyrotvOMyavjZAtYyVk8Apk9Tkj1dXB',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 2,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-12',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'AMLmwomZyetmZjnrmYVESQRoe3NpeLf6aZX7y',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 5,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-05-29',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'qkLwKNweJ5hdgzRVdP0nsEQxX8azXLUJYx8QR',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 935.63,
    authorized_date: null,
    category: ['Payment', 'Credit Card'],
    category_id: '16001000',
    date: '2020-07-02',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    merchant_name: null,
    name: 'WF Credit Card AUTO PAY 200702 90495290820055 HODNETT,HUNTER C',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'AMLmwomZyetmZjnrmYV6fRj76MbyYNI6dv5QQ',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 5,
    authorized_date: null,
    category: ['Transfer', 'Save As You Go'],
    category_id: '21013000',
    date: '2020-06-29',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    merchant_name: null,
    name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'mBZgLQgeoxTv8L0wv6KRHvjkJvD1XvFMgNPVX',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
    account_owner: null,
    amount: 2529.11,
    authorized_date: null,
    category: ['Payment', 'Rent'],
    category_id: '16002000',
    date: '2020-07-02',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    merchant_name: 'The Arnold',
    name: 'The Arnold WEB PMTS 070220 CR6PG6 Hunter Hodnett',
    payment_channel: 'online',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: 'vrBoJXoeL9i1N3BA1KxQHpV3N7gqYBCmo9Jz8',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
    account_owner: null,
    amount: 935.63,
    authorized_date: null,
    category: ['Transfer', 'Debit'],
    category_id: '21006000',
    date: '2020-06-22',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    merchant_name: null,
    name: 'BALANCE TRANSFER FOR ACCT ENDING IN 9214',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: null,
    transaction_code: null,
    transaction_id: '8Mo1bj1vw9t41EvB47xdcXrDKbOw31IyL185d',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  {
    account_id: '0MzEyBEPAJtm83zdmPxpSY0Y166jd6urZRkan',
    account_owner: null,
    amount: 10000,
    authorized_date: '2020-07-08',
    category: ['Transfer', 'Debit'],
    category_id: '21006000',
    date: '2020-07-08',
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    merchant_name: null,
    name:
      'ONLINE TRANSFER TO HODNETT H WAY2SAVE CHECKING XXXXXX3888 REF #IB08G6WCL5 ON 07/08/20',
    payment_channel: 'other',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    pending: false,
    pending_transaction_id: 'AMLmwomZyetmZjnrmYVyCgwZLpo87pC6PwQbN',
    transaction_code: null,
    transaction_id: '7zQg50gAd7srDLvqrZmOHoaJzRxkZNuQd6dNY',
    transaction_type: 'special',
    unofficial_currency_code: null,
  },
  // tslint:disable-next-line: max-file-line-count
];
