import moment from 'moment';

export default {
  accounts: [
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 166.45,
      authorized_date: null,
      category: ['Food and Drink', 'Restaurants'],
      category_id: '13005000',
      date: moment().format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Quadmed Inc.',
      name: 'QUADMED, INC. #...0055',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: true,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '6MoB8vBkagtjQp0xjbRoCn55B4Ne7xUagXX4b',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 40.37,
      authorized_date: moment().subtract(3, 'days').format('YYYY-MM-DD'),
      category: ['Service', 'Food and Beverage'],
      category_id: '18021000',
      date: moment().subtract(1, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'NY',
        store_number: null,
      },
      merchant_name: 'Grubhubkorienteres',
      name: 'GrubHub',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'L6vmZPmVweTEDQnxE6P7H0eow5Yoz6t0bEydO',
      transaction_code: null,
      transaction_id: 'mBZgLQgeoxTv8L0wv6KjhyaabkqLonsMg11Ln',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 1,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(1, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'zJko9QoeqYu31JBY305dibPP5NZwxkHO0bb6r',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 39.57,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(1, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET STORE T3342 #...0055',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: true,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'w43jZQjYDVcn63zKnkedTvNNeP0w1JfL0BBj5',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 12.24,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(2, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'ROYAL BLUE GROCERY EASTSIAUSTIN',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'DMPQq7QbAetOZmxBO83Dfjz8JJ88XqCZ4Q88j',
      transaction_code: null,
      transaction_id: 'L6vmZPmVweTEDQnxE6Pkh0zzr5ZEkLH0bXXnr',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 20,
      authorized_date: moment().subtract(3, 'days').format('YYYY-MM-DD'),
      category: ['Travel', 'Gas Stations'],
      category_id: '22009000',
      date: moment().subtract(2, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Wip.chat Loves You Singapore Sgp',
      name: 'Recurring Payment - WIP.CHAT LOVES YOU SINGAPORE SGP',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'DMPQq7QbAetOZmxBO83Df3bL5ePLqYHZxA4zK',
      transaction_code: null,
      transaction_id: 'L6vmZPmVweTEDQnxE6PzC0OmyvENb6I0LpMAQ',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 45.82,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(4, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '11220 Ranch Road 2222',
        city: 'Austin',
        country: null,
        lat: 30.398381,
        lon: -97.849938,
        postal_code: '78730',
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'Target',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'L6vmZPmVweTEDQnxE6P7HDXkKKkkLzU0yjpp6',
      transaction_code: null,
      transaction_id: 'KwA9J19XdesLZaAOLjVqTLzaXpO5LeCQR4pPA',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 97.68,
      authorized_date: null,
      category: ['Community', 'Government Departments and Agencies'],
      category_id: '12009000',
      date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'City of Austin T PAYMENT 200701 1415338965 HODNETT, HUNTER',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'n3dD1QDebJsNVxbANLkkTJdNOO6jnvIARbarq',
      transaction_code: null,
      transaction_id: 'aZKb8gbpJBsqXzvPqNV4FXw7b63qr0HZJyK1A',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 60,
      authorized_date: null,
      category: ['Shops', 'Digital Purchase'],
      category_id: '19019000',
      date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Gsuite_mokusho',
      name: 'GSUITE_mokusho cc@google.comCA',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: 'Google Wallet',
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'JdkOaDOVmeixkXrOxKDdFmM7YpQPAOcbJA078',
      transaction_code: null,
      transaction_id: 'QqaQEKQVPeURrXBdRLK5f3gOPPOOmnuEVoNNp',
      transaction_type: 'digital',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 14.48,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'ROYAL BLUE GROCERY EASTSIAUSTIN',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'xay9oQ9e1YTqLK5YqA8NFBNMo5x936UMwAmKP',
      transaction_code: null,
      transaction_id: '1Mozk3zqv8tKovypKxN1fA1kZZkkynsmyrXX5',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 1,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '0MzEyBEPAJtm83zdmPxZFyg61zrdbYUrZx9vp',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 31.16,
      authorized_date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      category: ['Travel', 'Gas Stations'],
      category_id: '22009000',
      date: moment().subtract(5, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Signature Lamar',
      name: 'SIGNATURE LAMAR',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'BRDNLbN5KeiLpVvrLPDBIYDZgP9gYks96pKEZ',
      transaction_code: null,
      transaction_id: '4MOE4kEyrotvOMyavjZNUnw45pLk7YfkP1Dn4',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 7.99,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(6, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'ROYAL BLUE GROCERY EASTSIAUSTIN',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '6MoB8vBkagtjQp0xjbRRi7R3XvRQbjSaJzVAn',
      transaction_code: null,
      transaction_id: 'O1r0930VDesA8V5LAw3dCQPVemeoJaT8dZpgB',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 29.95,
      authorized_date: moment().subtract(7, 'days').format('YYYY-MM-DD'),
      category: ['Service', 'Internet Services'],
      category_id: '18031000',
      date: moment().subtract(6, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'VA',
        store_number: null,
      },
      merchant_name: 'Siteground Hosting',
      name: 'Recurring Payment - SITEGROUND HOSTING',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'QqaQEKQVPeURrXBdRLKKCQaLOOr0ymhEYpdNw',
      transaction_code: null,
      transaction_id: '0MzEyBEPAJtm83zdmPx6f0mPBnjbKeCrgkEoD',
      transaction_type: 'digital',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 27.43,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(6, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '11220 Ranch Road 2222',
        city: 'Austin',
        country: null,
        lat: 30.398381,
        lon: -97.849938,
        postal_code: '78730',
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'Target',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'j1xdeQdmbrsp0wojp7ePSx1VbNdk8gFR0dMmB',
      transaction_code: null,
      transaction_id: 'VkmAdjAVKeh5MbXA5BjqHm0XexeqJDUr1znjB',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 12,
      authorized_date: null,
      category: ['Shops', 'Digital Purchase'],
      category_id: '19019000',
      date: moment().subtract(7, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Domains',
      name: 'Domains g.co/helppay#CA',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: 'Google Wallet',
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'w43jZQjYDVcn63zKnkeeHZbbXLyvNZHL0j3ar',
      transaction_code: null,
      transaction_id: '4MOE4kEyrotvOMyavjZbhyjMbmd71AHkmK68Q',
      transaction_type: 'digital',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 23.98,
      authorized_date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(7, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '247 W 3rd St',
        city: 'Austin',
        country: null,
        lat: 30.265617,
        lon: -97.74569,
        postal_code: '78701',
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'Royal Blue Grocery',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'QqaQEKQVPeURrXBdRLKpHB9evbqQBmHE0e04Q',
      transaction_code: null,
      transaction_id: 'BRDNLbN5KeiLpVvrLPDPCjma81D3KrU9Po16j',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 1,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(7, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'qkLwKNweJ5hdgzRVdP0PTagVbZKM0RtJmXQex',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 2,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(8, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'Xv6MD4MOAeTk0m8DkyeefBZon6VZ6YU4AvBeM',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 7.57,
      authorized_date: moment().subtract(8, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(8, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '4MOE4kEyrotvOMyavjZ1HMAX5L9jrphAd3ppe',
      transaction_code: null,
      transaction_id: 'NDjQgBQVLYcJjoQ1JdBBTpKZa34K3PtReNBqO',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 50.22,
      authorized_date: moment().subtract(8, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(8, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'aZKb8gbpJBsqXzvPqNV5cPRYb314J6Hjr6MMr',
      transaction_code: null,
      transaction_id: 'ed0KVQKeJkixKADyxZLLtEZz90gZ0YudmyvmJ',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 100,
      authorized_date: null,
      category: ['Service'],
      category_id: '18000000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'BUSINESS TO BUSINESS ACH ETC INC ACH 200626 AI30326 ETC INC',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: 'ACH',
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'dbvg7zgeRKsDBka3D86pfYZ3zY68MYSbXDRdY',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 2.25,
      authorized_date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      category: ['Service'],
      category_id: '18000000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'NY',
        store_number: null,
      },
      merchant_name: 'Digitalocean',
      name: 'DIGITALOCEAN.COM DIGITALOCEAN.',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'L6vmZPmVweTEDQnxE6PEcZDmLqm4VPUoEmaA9',
      transaction_code: null,
      transaction_id: 'ML0AoqAY6euBzK5PBYNrCZQ98ZBLmZCMZPY8a',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 87.09,
      authorized_date: moment().subtract(11, 'days').format('YYYY-MM-DD'),
      category: ['Service', 'Insurance'],
      category_id: '18030000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'DC',
        store_number: null,
      },
      merchant_name: 'GEICO',
      name: 'GEICO',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '6MoB8vBkagtjQp0xjbRjINYJxZJQPvC0dymvv',
      transaction_code: null,
      transaction_id: 'O1r0930VDesA8V5LAw3BSMKQEMwJvMf8d4RwE',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 65.85,
      authorized_date: moment().subtract(11, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '11521 N Fm 620   Ste A',
        city: 'Austin',
        country: null,
        lat: 30.455047,
        lon: -97.826012,
        postal_code: '78726',
        region: 'TX',
        store_number: '465',
      },
      merchant_name: 'H-E-B',
      name: 'H-E-B',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'w43jZQjYDVcn63zKnkenS05AJYAxbytdwyg9J',
      transaction_code: null,
      transaction_id: 'VkmAdjAVKeh5MbXA5Bj6iNamVNbJ7NUr1kxRx',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 4.54,
      authorized_date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      category: ['Service'],
      category_id: '18000000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'NY',
        store_number: null,
      },
      merchant_name: 'Postable',
      name: 'Recurring Payment - POSTABLE.COM 9173882735',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'PP4ZOyZV1ein4DXEn6ynSYvZayZ0EVHwp1Dnx',
      transaction_code: null,
      transaction_id: 'n3dD1QDebJsNVxbANLkKfEZM4EgP9EFAR79ro',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 15.98,
      authorized_date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '247 W 3rd St',
        city: 'Austin',
        country: null,
        lat: 30.265617,
        lon: -97.74569,
        postal_code: '78701',
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'Royal Blue Grocery',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'DMPQq7QbAetOZmxBO83Os0jpXQp1mKtYAV0nx',
      transaction_code: null,
      transaction_id: 'QqaQEKQVPeURrXBdRLK1uY5AoYNqbYSEYJrNv',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 27.56,
      authorized_date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'NDjQgBQVLYcJjoQ1JdB8iEwL5jpK86iRvrMoJ',
      transaction_code: null,
      transaction_id: 'RBx4Qk4EqeT8mwMK8DV7cMAXxMrB3Mfyx13Oj',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 21.28,
      authorized_date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      category: ['Travel', 'Tolls and Fees'],
      category_id: '22017000',
      date: moment().subtract(9, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Txtag',
      name: 'TXTAG',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '1Mozk3zqv8tKovypKxNKszAvy5vM7EHbajERy',
      transaction_code: null,
      transaction_id: 'EMqJ39JgvetYozNrYvM8SQBOaQo49QHpmEDgo',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 100,
      authorized_date: null,
      category: ['Transfer', 'Debit'],
      category_id: '21006000',
      date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name:
        'RECURRING TRANSFER TO HODNETT H REF #OP08CWCMDJ WAY2SAVE SAVINGS SAVINGS',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'j1xdeQdmbrsp0wojp7eVCvY3EJRpOnCR44AV9',
      transaction_code: null,
      transaction_id: 'DMPQq7QbAetOZmxBO831SVOVe41a6JfZJ7Dn3',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 2,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'L6vmZPmVweTEDQnxE6PAhgEg5R4NrKI096eA7',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 41.1,
      authorized_date: moment().subtract(13, 'days').format('YYYY-MM-DD'),
      category: ['Food and Drink', 'Restaurants'],
      category_id: '13005000',
      date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Sushi Zushi Of Fif',
      name: 'SUSHI ZUSHI OF FIF',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'ed0KVQKeJkixKADyxZLBsgNrQMV3OLudDMrOE',
      transaction_code: null,
      transaction_id: 'PP4ZOyZV1ein4DXEn6yrTMnMLp063qCmXYenp',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 44.44,
      authorized_date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(12, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'w43jZQjYDVcn63zKnkeMfJ8EkDDRV4fL0bO4L',
      transaction_code: null,
      transaction_id: '1Mozk3zqv8tKovypKxNVS939eDM8JZHm3dpR0',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 7,
      authorized_date: null,
      category: ['Service', 'Financial', 'Banking and Finance'],
      category_id: '18020012',
      date: moment().subtract(13, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name:
        'BUSINESS TO BUSINESS ACH Truebill Truebill P ST-S4X5J9N7W8Q5 TRUEBILL INC',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: 'ACH',
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'rmD7AY7eJohn45Vmnqj3i8zX93Zy4ACByyYJX',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: '0MzEyBEPAJtm83zdmPxpSY0Y166jd6urZRkan',
      account_owner: null,
      amount: 0.05,
      authorized_date: null,
      category: ['Tax', 'Payment'],
      category_id: '20002000',
      date: moment().subtract(14, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Federal Tax',
      name: 'FEDERAL TAX WITHHELD',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'ML0AoqAY6euBzK5PBYNATXjywK65LDfM3LPMR',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 22.98,
      authorized_date: moment().subtract(16, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(14, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '247 W 3rd St',
        city: 'Austin',
        country: null,
        lat: 30.265617,
        lon: -97.74569,
        postal_code: '78701',
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Royal Blue Grocery',
      name: 'Royal Blue Grocery',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'vrBoJXoeL9i1N3BA1KxbTLnoXOQ5xaHmEyrPn',
      transaction_code: null,
      transaction_id: 'O1r0930VDesA8V5LAw3PIa0k7Od8J5s8K048e',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 2,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(16, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '7zQg50gAd7srDLvqrZmEF5qvwd0b8nuQmoYQ4',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 44.57,
      authorized_date: moment().subtract(16, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(16, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Target',
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'O1r0930VDesA8V5LAw3ph99g63v3OzU8d668A',
      transaction_code: null,
      transaction_id: 'VkmAdjAVKeh5MbXA5Bj9HD15vMwrJOtrNbkrk',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 138.34,
      authorized_date: null,
      category: ['Service', 'Telecommunication Services'],
      category_id: '18063000',
      date: moment().subtract(16, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: 'Verizon Wireless',
      name: 'Verizon Wireless',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '9Mo97r906VtaK1R5aQA9Hw6KXNexdoTdb3ydr',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 1,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(17, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'O1r0930VDesA8V5LAw3ph1KoVQm4azU86Xw6x',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 50.76,
      authorized_date: moment().subtract(18, 'days').format('YYYY-MM-DD'),
      category: ['Food and Drink', 'Restaurants'],
      category_id: '13005000',
      date: moment().subtract(17, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: 'Sushi Zushi Of Fif',
      name: 'SUSHI ZUSHI OF FIF',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'j1xdeQdmbrsp0wojp7eyUBQRP6pK3EUR9za8k',
      transaction_code: null,
      transaction_id: 'ML0AoqAY6euBzK5PBYNpfrQxM9qPXefMjD8j0',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 3,
      authorized_date: null,
      category: ['Transfer', 'Save As You Go'],
      category_id: '21013000',
      date: moment().subtract(18, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: 'SAVE AS YOU GO TRANSFER DEBIT TO XXXXXXXXXXX3523',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'bmkK57Ken3hjrqwKjxdbFepv3AgPbZhqb6RA3',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 38.48,
      authorized_date: moment().subtract(17, 'days').format('YYYY-MM-DD'),
      category: ['Food and Drink', 'Restaurants'],
      category_id: '13005000',
      date: moment().subtract(19, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'SUSHI ZUSHI OF FIF',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'BRDNLbN5KeiLpVvrLPD0hA3oKgXAv7S9D8NBA',
      transaction_code: null,
      transaction_id: '9Mo97r906VtaK1R5aQAxSV5JbMLwgXCd7XnaZ',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 30.56,
      authorized_date: moment().subtract(19, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(19, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '0MzEyBEPAJtm83zdmPxQTAvaLyMgrYSr37RP8',
      transaction_code: null,
      transaction_id: '7zQg50gAd7srDLvqrZmaig7NOoa5DwTQP3gOn',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 35.51,
      authorized_date: moment().subtract(22, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(19, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TARGET ST 901 E 5th St',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: '3eoOjKO3m5UAV7npAOZ4H908dEb9gDTKvzL1a',
      transaction_code: null,
      transaction_id: 'g6rARQAeJvT8yVN98o1DTnBQP63kwrCq7XNZk',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 22.29,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(17, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'ROYAL BLUE GROCERY EASTSIAUSTIN',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'QqaQEKQVPeURrXBdRLK8i157zAxJmgUEZgNZw',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 24.99,
      authorized_date: null,
      category: ['Shops', 'Computers and Electronics', 'Video Games'],
      category_id: '19013001',
      date: moment().subtract(18, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'WA',
        store_number: null,
      },
      merchant_name: null,
      name: 'Steam Games',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'ZjDvBxvV0wSvrndbvkxAIwdA96V0p7cRA4oQ1',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 3.18,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(21, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: 'Austin',
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'ROYAL BLUE GROCERY EASTSIAUSTIN',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'oyw1qQ1eJ8t6yPQJ6DA8TyAobraL9PcBxJgaN',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'pK6d3ndeJZs6R9ED61vbTn5RJnZjBxUJVeRXb',
      account_owner: null,
      amount: 38.42,
      authorized_date: null,
      category: ['Shops', 'Supermarkets and Groceries'],
      category_id: '19047000',
      date: moment().subtract(21, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '11220 Ranch Road 2222',
        city: 'Austin',
        country: null,
        lat: 30.398381,
        lon: -97.849938,
        postal_code: '78730',
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'Target',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '5MoExAEK4bt0KMQa068NIJePqz7XQDCBXDMLv',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 7.33,
      authorized_date: moment().subtract(26, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(22, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '247 W 3rd St',
        city: 'Austin',
        country: null,
        lat: 30.265617,
        lon: -97.74569,
        postal_code: '78701',
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'Royal Blue Grocery',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: 'pK6d3ndeJZs6R9ED61vZU5AvyNEXgaiJ0AQE0',
      transaction_code: null,
      transaction_id: '3eoOjKO3m5UAV7npAOZ0tXaEVJdvNqtKY3Kd3',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 25,
      authorized_date: moment().subtract(26, 'days').format('YYYY-MM-DD'),
      category: ['Community', 'Education', 'Primary and Secondary Schools'],
      category_id: '12008003',
      date: moment().subtract(25, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: '321 W Ben White Blvd',
        city: 'Austin',
        country: null,
        lat: 30.223644,
        lon: -97.767426,
        postal_code: '78704',
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'Central Texas Gun Works',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'vrBoJXoeL9i1N3BA1Kx9SapLZXB9ZAtmLYnQ4',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 20.67,
      authorized_date: moment().subtract(26, 'days').format('YYYY-MM-DD'),
      category: ['Service', 'Insurance'],
      category_id: '18030000',
      date: moment().subtract(25, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'NY',
        store_number: null,
      },
      merchant_name: null,
      name: 'LEMONADE I* LEMONA LEMONADE.COM',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '0MzEyBEPAJtm83zdmPxpSY0AdLezd9Tr1xdbq',
      transaction_type: 'special',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 19.68,
      authorized_date: moment().subtract(29, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(27, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TST* BLENDERS AND',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'aZKb8gbpJBsqXzvPqNVAs0QgqmR6q1FZqyr8E',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 71.95,
      authorized_date: moment().subtract(30, 'days').format('YYYY-MM-DD'),
      category: ['Service'],
      category_id: '18000000',
      date: moment().subtract(28, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'CA',
        store_number: null,
      },
      merchant_name: null,
      name: 'NORDIC ONLINE STOR',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'ZjDvBxvV0wSvrndbvkxQted0ox7gopHRyzp0M',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 118.5,
      authorized_date: moment().subtract(29, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(28, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'CA',
        store_number: null,
      },
      merchant_name: null,
      name: 'PRESSED JUICERY, I',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '8Mo1bj1vw9t41EvB47xLi4rwkA1ak3Hy7mjdo',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 19.68,
      authorized_date: moment().subtract(30, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(28, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TST* BLENDERS AND',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '5MoExAEK4bt0KMQa068ds0eXnBDanQFBEb5q7',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 109.52,
      authorized_date: moment().subtract(31, 'days').format('YYYY-MM-DD'),
      category: ['Service'],
      category_id: '18000000',
      date: moment().subtract(29, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'NY',
        store_number: null,
      },
      merchant_name: null,
      name: 'BOXED.COM',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '7zQg50gAd7srDLvqrZmJTp75AXwdADUQK4py0',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 17.43,
      authorized_date: moment().subtract(30, 'days').format('YYYY-MM-DD'),
      category: ['Food and Drink', 'Restaurants'],
      category_id: '13005000',
      date: moment().subtract(31, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'CA',
        store_number: null,
      },
      merchant_name: null,
      name: 'Chipotle Mexican Grill',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'bmkK57Ken3hjrqwKjxdyUKpPV8Z1VbCq4xKp6',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 20.34,
      authorized_date: moment().subtract(30, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(29, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TST* BLENDERS AND',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'g6rARQAeJvT8yVN98o1qUDBkeLr4ewCqQMngq',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
    {
      account_id: 'vrBoJXoeL9i1N3BA1Kx9SapaJmmgZmsmxr9j6',
      account_owner: null,
      amount: 22.19,
      authorized_date: moment().subtract(33, 'days').format('YYYY-MM-DD'),
      category: ['Shops', 'Food and Beverage Store'],
      category_id: '19025000',
      date: moment().subtract(30, 'days').format('YYYY-MM-DD'),
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: 'TX',
        store_number: null,
      },
      merchant_name: null,
      name: 'TST* BLENDERS AND',
      payment_channel: 'online',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '9Mo97r906VtaK1R5aQADsa5wk0XNkgtdNPwA6',
      transaction_type: 'place',
      unofficial_currency_code: null,
    },
  ],
  status_code: 200,
};
